services:
  busybox:
    image: busybox
    container_name: host_hbelle
    networks:
      - badass

  frr:
    build:
      context: ./frrouting
      dockerfile: Dockerfile
    volumes:
      - ./frrouting/frr.conf:/etc/frr/frr.conf
      - ./frrouting/daemons:/etc/frr/daemons
    command: "chown -R frr:frr /etc/frr && \
              chmod 640 /etc/frr/frr.conf && \
              chmod 640 /etc/frr/daemons && \
              chmod +x start.sh"
    entrypoint: ["/bin/bash", "-c", "start.sh"]
    container_name: routeur_hbelle
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    privileged: true
    ports:
      - "179:179"
      - "2601:2601"
      - "2604-2610:2604-2610"
    networks:
      - badass

networks:
  badass:
    driver: bridge