# This configuration file is for FRRouting (FRR), an open-source routing software suite.
# 
# General Settings:
# - `frr version 10.2`: Specifies the version of FRR being used.
# - `frr defaults traditional`: Sets the default behavior to traditional mode.
# - `hostname frr-router`: Sets the hostname of the router to "frr-router".
# - `service integrated-vtysh-config`: Enables integrated configuration mode for vtysh.
# - `ip forwarding`: Enables IP forwarding on the router.
#
# BGP Configuration:
# - `router bgp 65000`: Configures BGP with Autonomous System (AS) number 65000 (65000 is a private AS number wich can be used for testing).
# - `bgp router-id 10.0.0.1`: Sets the BGP router ID to 10.0.0.1.
#
# OSPF Configuration:
# - `router ospf`: Enables OSPF routing protocol.
# - `network 10.0.0.0/24 area 0`: Specifies the OSPF network 10.0.0.0/24 in area 0.
#
# IS-IS Configuration:
# - `router isis 1`: Enables IS-IS routing protocol with process ID 1.
# - `net 49.0001.0000.0000.0001.00`: Configures the IS-IS NET address.
#
# Line Configuration:
# - `line vty`: Configures virtual terminal (vty) lines for remote access.

frr version 10.2
frr defaults traditional
!
hostname frr-router
!
service integrated-vtysh-config
!
ip forwarding
!
!
router bgp 65000
 bgp router-id 10.0.0.1
!
router ospf
 network 10.0.0.0/24 area 0
!
router isis 1
 net 49.0001.0000.0000.0001.00
!
line vty
!